default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: juliansmith
  password: password
  host: localhost
development:
  <<: *default
  database: filekeep-api
test:
  <<: *default
  database: filekeep-api-test
production:
  <<: *default
